# Generated by Django 5.0.3 on 2024-03-18 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='file',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post', to='first_project.postfilesmodel', verbose_name='Файл'),
        ),
    ]
